help:
  rails_help_href: "http://www.railstutorial.org/help"
  rails_book_href: "http://www.railstutorial.org/book"

home:
  rails_org_href: "http://www.railstutorial.org/"

users:
  email_href: "http://gravatar.com/emails"
  per_page: 5
  show:
    img_size: 50
  img_size: 50

expires_token: 1

follower:
  per_page: 5
following:
  per_page: 5
